language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install oracle-java8-installer

notifications:
  email: false