language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

before_script:
    - chmod +x gradlew
    - chmod +x .script/deploy_artifacts.sh

script:
  - ./gradlew clean build --info
  - ./gradlew build jacocoTestReport
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .script/deploy_artifacts.sh

notifications:
  email: false

env:
  global:
    - secure: cM6JOKS5y8BYLfMukxEQTVtdNFWe+LK6LfxYLLaGmPYPIqTiC2ubVciq/BozzgisgrPqie1MP2ncy/Gpoq7zlPdSfiGU/w9wGccz3s9gvvMvD8kTzLRrZxdvhlxajzU1TXG5KRyKHFh6BPEPA0w4xiwPRVUrSGh+J7muC1LoafmwG22tsmZ7JJvjsFKdMpdnxlI0qeW/kHVFolOlBxJRHGHiiYjU3ADwzakmBg4dwe6YmjncHdpQuOVNbyGCKyI6KMOMru3Yp1W5cQbHraayqek6KBzGS2M1JSWfNbfihoXyMBRRMSQjCEro/EAEZ/d2XOeSU5jr9CtFG3KWuPae84fXD7cUYxgNd9SReGUv2eEaAe1FU6/YHMC7nzz8eyoVW53wjbAOjrkei2hvO1FcgkRUVEdeHqIaflh/ER6MMz/OwCPBtHWq6XqiqCuwjqA8qYZ+OUhQA7LJb7fojwCdry/Hah81eRqyiBbq0RQDtRVvhXjVT6S/s9uWaNZtgkF6a93KXKgBiegBGSW6V+Mj0pkJb3jiJ+/w+vKHxoG+eDwUS4xcgNcj1sTYw+Vmh0KerasO11ogM4s3dCSquK6lSWFz4RVDblJxIubhxnSpnQtb8huJLjTlOeITnFeduPNJd1+drRaiw61B/B3vBBa0nHSOHPWCoL+ySRplVnme1F4=
    - secure: PbBsbi6DZmHkSyn6hSRFEJZ837ypy2gtHiJaed1BTIs+H5/DofMFYUvu/0zIeNY44G5RH7O4SoFhUzV8gQvA5VRs67jXIT4RR4SSLHdZsR95PSEksMEstRpIDddFI8XzXOvRT+4ZpNUH2DI7rs1uN2OhnaUoHqJeaaeYpQpNxNp4PxJn8IOAJmEcOqXkgKi94MPtJUy8pLTQspwu3wqo8YrR4NMziG4q9gzi5i80s3ZWR104sqm6RkuQuS+cWJAiK4b41DAt95RPtQWTTWCm+Aybn50tqbjrtVxCKiJYmgEoM6q5/KYxoWQbz+pCrF3320sYrXCeKiUyiXOOtL3zawyICEni/K3bSAWJoJYOoMhZ/dsuvZD/B+knnMtU09Sgko629RST/nd60RV8WOwGuDMr6eH4ApouvOdggQBgicLDqbIzlWF8XnPPByKmx1r/UICaGGNtT6EKxvqtGp4uOI5tFeqUHUrAW4HkylJcobZOFn28STlcw6en/yS4bsIve7Zi2xJK61Ydai/lkpt3hfWEFrNnX2jleFX+a2+bFzbGGZvsyEYT0M6TaPInxwAPaXK/YojlosecxVe2zpRYARZqimKMRdXgSqPAcHTrjCjTVYA+PanJOdtqbqQXYNeKnbuEKN38tJzvfxfFpYGtKXhJ3ww9Gh34t8bQs0t+Jps=
    - secure: ccYuVdV4/jTB3nogOGWIc8rc/HjAPVftY3VaeqEYevq/u1vvfWZoVPb0EbvKVeymuGrUI2rbqlWg6F1OS5HuLC/YRYboR3IkH2nXHhXEzrclPTj6e2fyu+da0pxgQk9+T/KuBRuy3sTv6yzQZPXtaSdUJAzVLrkK05tyJ0cqV9IbQGG4VPqWyy5jInvyuRo67U+/6dX7R8V4CxwD4l0IUiMoIscwvM4pn8HvKoCVskzeYJ7SFERaybnUbzkIKFUHT5fTNXmi26sqW+4/heHigPG/HJMJt0rqBJfJQO3qBecH1jPoxc68jZjXNzwzDvrXvE/DDWtmBEkFYv75IVZci8eCxcpCDE8ipKdSo4Tt8EwzozQqVt5DpwWa/XtQbnCrVjZx73XfmSDRTntnZFwJvLvCvWApP2asXmOz3vME04uKhKmOli6ZP8o0HWwai/sNxxd9dnfeKGtH0eKW04sWf2anK6YQmkNgzJmBN8GhrbqokXRqJJB0+jmX+HUH5IUBH1aiSKAm1xGsfrtr/0qN1oufmiO4xxPA71g2X8+NguGjeJPs+4Wg5ir2unvbHfDb/pyl9fEuk9qusEdhP7Yj+fFaw58s9YyTy9yJJMA/NaNamhjDSRfHwEebI6Ha9wq86ktnVnT774Gv6AEHTg3AB9fpwJxVEvJ7hWNSelwY/gY=
